### PR TITLE
Migrated appwrite^6.0.0 to appwrite^8.1.0

### PR DESCRIPTION
**Pull request by skdotv**
## What does this PR do?
Upgraded Appwrite SDK from 6.0.0 to 8.1.0(Latest)

(Provide a description of what this PR does.)

## Test Plan

(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work.)
After upgrading the sdk,
Ran the application,
- Registered User : worked
- Completed login : worked
- monitored debug console for errors while navigating in the application: worked 

## Related PRs and Issues
 Resolves this =>   Feature: Upgrade Appwrite SDK 6.0.0 to latest SDK 8.1.0 #3
(If this PR is related to any other PR or resolves any issue or related to any issue link all related PR and issues here.)

### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?
yes
(Write your answer here.)

### CODE REVIEW

**Comment by stnguyen90** [comment]
We will not be accepting this PR for Hacktoberfest unless everyone else who commented in https://github.com/appwrite/appwrite/issues/4269 has had an opportunity to try to upgrade this repo in the order requested.

**Comment by skdotv** [comment]
@stnguyen90  sounds good. next time I will pick issues from the main repository i.e (appwrite) and then contribute to the repository.

**Comment by Meldiron** [comment]
Thank you so much for the PR 🤩. We're adding the `hacktoberfest-accepted` label to ensure this PR counts towards your Hacktoberfest contributions count. With that said, please stay active on this PR to address any comments once you receive a review. Happy Hacktoberfest! 🎃

**Comment by christyjacob4** [comment]
@skdotv thanks for the PR but it look like another user had been assigned to complete the PR. I will have to close this PR. 

You can however reach out to me on Discord to claim your swag

**Pull request closed without merging**
